name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
      TRITON_SERVER: ${{ secrets.TRITON_SERVER }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mypy ruff bandit beautifulsoup4>=4.9.0 requests>=2.25.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Lint check
        run: |
          # exit-zero treats all errors as warnings.
          ruff check --config ruff.toml --select I src tests --exit-zero
          ruff check --config ruff.toml src tests --exit-zero
      - name: Type check
        run: |
          # exit-zero treats all errors as warnings.
          mypy --config-file mypy.ini src || true
      - name: Security check
        run: |
          # exit-zero treats all errors as warnings.
          bandit -r src --exit-zero
      - name: Test
        run: |
          # install local module
          pip install .
          # test with Pytest
          pytest
